objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Books</relationshipLabel>
        <relationshipName>Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/x_product__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>x products</relationshipLabel>
        <relationshipName>x_products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>x products</relationshipLabel>
        <relationshipName>x_products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>x product</label>
    <nameField>
        <label>x_product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>x products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/XProductHelperClass.cls
public with sharing class XProductHelperClass {

	public ID URL_ID {get; set;}

 //   private ApexPages.StandardController stdctrl;
    private Schema.SObjectType caseType = Schema.getGlobalDescribe().get('case');
    private Schema.SObjectType bookType = Schema.getGlobalDescribe().get('gdansf14383017__Book__c');

	public XProductHelperClass (ApexPages.StandardController stdController) {
//		this.stdctrl = stdController;
		String str = System.currentPageReference().getParameters().get('retURL').substring(1,16); // get the parent ID from URL
		URL_Id = (Id)str;
	}
	
	public PageReference save() {
		system.debug('2');
		system.debug('id: ' + URL_ID);
		system.debug('URL_ID.getSobjectType(): ' + URL_ID.getSobjectType());
     	x_Product__c x_Product;
     	if (URL_ID.getSobjectType() == caseType)
 			x_Product = new x_Product__c(case__c = URL_ID);
		else if (URL_ID.getSobjectType() == bookType)
 			x_Product = new x_Product__c(book__c = URL_ID);
		insert x_Product;
		return new ApexPages.StandardController(x_Product).view();
	}
}